// Prop definition
export * from './prop-def';

// Individual props
export * from './as-child.prop';
export * from './color.prop';
export * from './gap.props';
export * from './height.props';
export * from './high-contrast.prop';
export * from './layout.props';
export * from './leading-trim.prop';
export * from './margin.props';
export * from './padding.props';
export * from './radius.prop';
export * from './text-align.prop';
export * from './text-wrap.prop';
export * from './truncate.prop';
export * from './weight.prop';
export * from './width.props';

// // Component props
// export * from '@components/radix/alert-dialog.props';
// export * from '@components/radix/avatar.props';
// export * from '@components/radix/badge.props';
// export * from '@components/radix/blockquote.props';
// export * from '@components/radix/box.props';
// export * from '@components/radix/button.props';
// export * from '@components/radix/callout.props';
// export * from '@components/radix/card.props';
// export * from '@components/radix/checkbox-cards.props';
// export * from '@components/radix/checkbox-group.props';
// export * from '@components/radix/checkbox.props';
// export * from '@components/radix/code.props';
// export * from '@components/radix/container.props';
// export * from '@components/radix/context-menu.props';
// export * from '@components/radix/data-list.props';
// export * from '@components/radix/dialog.props';
// export * from '@components/radix/dropdown-menu.props';
// export * from '@components/radix/em.props';
// export * from '@components/radix/flex.props';
// export * from '@components/radix/grid.props';
// export * from '@components/radix/heading.props';
// export * from '@components/radix/hover-card.props';
// export * from '@components/radix/icon-button.props';
// export * from '@components/radix/inset.props';
// export * from '@components/radix/kbd.props';
// export * from '@components/radix/link.props';
// export * from '@components/radix/popover.props';
// export * from '@components/radix/progress.props';
// export * from '@components/radix/quote.props';
// export * from '@components/radix/radio.props';
// export * from '@components/radix/radio-cards.props';
// export * from '@components/radix/radio-group.props';
// export * from '@components/radix/scroll-area.props';
// export * from '@components/radix/section.props';
// export * from '@components/radix/segmented-control.props';
// export * from '@components/radix/select.props';
// export * from '@components/radix/separator.props';
// export * from '@components/radix/skeleton.props';
// export * from '@components/radix/slider.props';
// export * from '@components/radix/spinner.props';
// export * from '@components/radix/strong.props';
// export * from '@components/radix/switch.props';
// export * from '@components/radix/tab-nav.props';
// export * from '@components/radix/table.props';
// export * from '@components/radix/tabs.props';
// export * from '@components/radix/text-area.props';
// export * from '@components/radix/text-field.props';
// export * from '@components/radix/text.props';
// export * from '@components/radix/theme.props';
// export * from '@components/radix/tooltip.props';
